// cmd/djangogo/main.go
// Command djangogo is the Djan-Go-Go management CLI. In a real project this is
// generated by `startproject` with the project's settings and apps; for now it
// boots a demo application so the framework is runnable.
package main

import (
	"fmt"
	"os"

	"github.com/oliverhaas/djangogo"
	"github.com/oliverhaas/djangogo/conf"
)

func main() {
	app, err := djangogo.New(conf.Settings{
		Debug:     true,
		SecretKey: "dev-insecure-key-change-me",
	})
	if err != nil {
		fmt.Fprintln(os.Stderr, "error:", err)
		os.Exit(1)
	}
	if err := app.Execute(os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, "error:", err)
		os.Exit(1)
	}
}
